---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: appname-api-hom
  namespace: dev
  labels:
    app: appname-api-hom
    env: homologacao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appname-api-hom
      env: homologacao
  template:
    metadata:
      labels:
        app: appname-api-hom
        env: homologacao
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "1234"
    spec:
      hostAliases:
      - ip: "10.8.26.97"
        hostnames:
        - "oracle-apoio"
        - "oracle-apoio.trt8.net"
      containers:
      - name: appname-api-hom-container
        image: registry.trt8.jus.br/desenvolvimento/appname/appname-api:<IMAGE_VERSION>
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: CONTEXT_PATH
          value: "/appname-api"
        - name: DEFAULT_TIMEZONE
          value: "America/Belem"
        - name: DEFAULT_LOCALE
          value: "pt-BR"          
        - name: FLYWAY_ENABLED
          value: "true"
        - name: FLYWAY_CREATE_SCHEMA
          value: "false"
        - name: DB_DRIVER_CLASS_NAME
          value: "oracle.jdbc.OracleDriver"
        - name: JPA_DIALECT
          value: "org.hibernate.dialect.Oracle12cDialect"
        - name: DB_URL
          value: ${DB_URL}
        - name: DB_SCHEMA
          value: "APPNAME"
        - name: DB_USERNAME
          value: ${DB_USERNAME}
        - name: DB_PASSWORD
          value: ${DB_PASSWORD}                  
        - name: MAIL_HOST
          value: ${MAIL_HOST}
        - name: MAIL_PORT
          value: ${MAIL_PORT}        
        - name: JPA_SHOW_SQL
          value: ${JPA_SHOW_SQL}
        - name: LOGGING_LEVEL
          value: ${LOGGING_LEVEL}                                        
        - name: KEYCLOAK_REALM
          value: ${KEYCLOAK_REALM}
        - name: KEYCLOAK_AUTH_SERVER_URL
          value: ${KEYCLOAK_AUTH_SERVER_URL}
        - name: KEYCLOAK_RESOURCE_API
          value: ${KEYCLOAK_RESOURCE_API}                
        - name: INTEGRACOES_KEYCLOAK_URL
          value: ${INTEGRACOES_KEYCLOAK_URL}
        - name: INTEGRACOES_SIGEP_URL
          value: ${INTEGRACOES_SIGEP_URL}                              
---
kind: Service
apiVersion: v1
metadata:
  name: appname-api-hom-service
  namespace: dev
  labels:
    app: appname-api-hom
    env: homologacao
  annotations:
    kubernetes.io/ingress.class: nginx  
spec:
  selector:
     app: appname-api-hom
     env: homologacao
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080

