version: '3'
services:         
  postgres-appname:
    image: postgres
    container_name: postgres-appname-local    
    volumes:
     # - ./postgres/scripts:/docker-entrypoint-initdb.d
      - ./postgres/data:/var/lib/postgresql/data
    environment:               
      POSTGRES_MULTIPLE_DATABASES: localdb,keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      - local-network

  keycloak-appname:
    image:  bitnami/keycloak:16.1.0
    container_name: keycloak-appname-local                
    volumes:                  
      - ./keycloak/import:/import      
     # - ./keycloak/scripts:/docker-entrypoint-initdb.d
      
    environment:                        
      KEYCLOAK_CREATE_ADMIN_USER: true
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: admin    
      KEYCLOAK_DATABASE_VENDOR: postgresql
      KEYCLOAK_DATABASE_HOST: postgres-appname
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_USER: postgres
      KEYCLOAK_DATABASE_PASSWORD: postgres
      KEYCLOAK_DATABASE_SCHEMA: public
      KEYCLOAK_EXTRA_ARGS: -Dkeycloak.profile.feature.scripts=enabled
    ports:
      - 8280:8080
    depends_on:
      - postgres-appname            
    networks:
      - local-network        
      
networks:
  local-network:
    name: local-network    